name: BombingEyes
version: 1.0-SNAPSHOT
main: net.kunmc.lab.bombingeyes.BombingEyes
api-version: 1.15

commands:
  be-in:
    description: "視界内爆破モードON"
    permission: OP
  be-out:
    description: "視界外爆破モードON"
    permission: OP
  be-off:
    description: "爆破モードOFF"
    permission: OP
  be-reload:
    description: "コンフィグリロード"
    permission: OP

permissions:
  OP:
    default: op